version: '3'
networks:
  app-network:
    driver: bridge
services:
  redis:
    image: gcr.io/saad-375811/redis 
    networks:
      - app-network
    ports:
      - 6379:6379    
  tornado:
    build: 
      context: .
      dockerfile: Dockerfile
    image: gcr.io/saad-375811/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - ENVIRONMENT=DEV
      - HOST='0.0.0.0'
      - PORT=8000
    ports:
      - 8000:8000
    depends_on:
      - redis
    networks:
      - app-network 
    